const cityLookup = {
    "KIGALI": "KGL",
    "NAIROBI": "NBO",
    "KAMPALA": "EBB",
    "ENTEBBE": "EBB",
    "DAR ES SALAAM": "DAR",
    "ZANZIBAR": "ZNZ",
    "MOMBASA": "MBA",
    "BUJUMBURA": "BJM",
    "ADDIS ABABA": "ADD",
    "JUBA": "JUB",
    "MOGADISHU": "MGQ",
    "DJIBOUTI": "JIB",
    "KILIMANJARO": "JRO",
    "ARUSHA": "JRO",
    "KAMEMBE": "KME",
    "ELDORET": "EDL",
    "KISUMU": "KIS",
    "MWANZA": "MWZ",
    "LAGOS": "LOS",
    "ABUJA": "ABV",
    "ACCRA": "ACC",
    "DAKAR": "DSS",
    "ABIDJAN": "ABJ",
    "DOUALA": "DLA",
    "YAOUNDE": "NSI",
    "LIBREVILLE": "LBV",
    "LOME": "LFW",
    "COTONOU": "COO",
    "BAMAKO": "BKO",
    "CONAKRY": "CKY",
    "FREETOWN": "FNA",
    "MONROVIA": "ROB",
    "NIAMEY": "NIM",
    "OUAGADOUGOU": "OUA",
    "PORT HARCOURT": "PHC",
    "JOHANNESBURG": "JNB",
    "CAPE TOWN": "CPT",
    "DURBAN": "DUR",
    "LUSAKA": "LUN",
    "HARARE": "HRE",
    "MAPUTO": "MPM",
    "LILONGWE": "LLW",
    "BLANTYRE": "BLZ",
    "WINDHOEK": "WDH",
    "GABORONE": "GBE",
    "LUANDA": "LAD",
    "CAIRO": "CAI",
    "CASABLANCA": "CMN",
    "TUNIS": "TUN",
    "ALGIERS": "ALG",
    "MARRAKECH": "RAK",
    "SHARM EL SHEIKH": "SSH",
    "HURGHADA": "HRG",
    "TRIPOLI": "TIP",
    "KHARTOUM": "KRT",
    "KINSHASA": "FIH",
    "BRAZZAVILLE": "BZV",
    "BANGUI": "BGF",
    "NDJAMENA": "NDJ",
    "LUBUMBASHI": "FBM",

    "DUBAI": "DXB",
    "ABU DHABI": "AUH",
    "DOHA": "DOH",
    "JEDDAH": "JED",
    "RIYADH": "RUH",
    "MUSCAT": "MCT",
    "KUWAIT": "KWI",
    "BAHRAIN": "BAH",
    "AMMAN": "AMM",
    "BEIRUT": "BEY",
    "TEL AVIV": "TLV",

    "LONDON": "LHR",
    "PARIS": "CDG",
    "AMSTERDAM": "AMS",
    "FRANKFURT": "FRA",
    "BRUSSELS": "BRU",
    "ZURICH": "ZRH",
    "ROME": "FCO",
    "MADRID": "MAD",
    "BARCELONA": "BCN",
    "ISTANBUL": "IST",
    "LISBON": "LIS",
    "ATHENS": "ATH",
    "BERLIN": "BER",
    "MUNICH": "MUC",
    "VIENNA": "VIE",
    "DUBLIN": "DUB",
    "COPENHAGEN": "CPH",
    "STOCKHOLM": "ARN",
    "OSLO": "OSL",
    "HELSINKI": "HEL",
    "WARSAW": "WAW",
    "PRAGUE": "PRG",
    "BUDAPEST": "BUD",
    "MILAN": "MXP",
    "GENEVA": "GVA",
    "MOSCOW": "SVO",
    "EDINBURGH": "EDI",
    "MANCHESTER": "MAN",

    "MUMBAI": "BOM",
    "DELHI": "DEL",
    "BANGALORE": "BLR",
    "CHENNAI": "MAA",
    "KOLKATA": "CCU",
    "TOKYO": "HND",
    "OSAKA": "KIX",
    "BEIJING": "PEK",
    "SHANGHAI": "PVG",
    "HONG KONG": "HKG",
    "SINGAPORE": "SIN",
    "BANGKOK": "BKK",
    "KUALA LUMPUR": "KUL",
    "JAKARTA": "CGK",
    "SEOUL": "ICN",
    "TAIPEI": "TPE",
    "MANILA": "MNL",
    "HANOI": "HAN",
    "HO CHI MINH": "SGN",

    "NEW YORK": "JFK",
    "LOS ANGELES": "LAX",
    "CHICAGO": "ORD",
    "MIAMI": "MIA",
    "ATLANTA": "ATL",
    "SAN FRANCISCO": "SFO",
    "WASHINGTON": "IAD",
    "BOSTON": "BOS",
    "HOUSTON": "IAH",
    "DALLAS": "DFW",
    "DENVER": "DEN",
    "SEATTLE": "SEA",
    "TORONTO": "YYZ",
    "MONTREAL": "YUL",
    "VANCOUVER": "YVR",
    "MEXICO CITY": "MEX",
    "SAO PAULO": "GRU",
    "RIO DE JANEIRO": "GIG",
    "BUENOS AIRES": "EZE",
    "BOGOTA": "BOG",
    "LIMA": "LIM",
    "SANTIAGO": "SCL",

    "SYDNEY": "SYD",
    "MELBOURNE": "MEL",
    "AUCKLAND": "AKL",
    "PERTH": "PER",
    "BRISBANE": "BNE"
};